services:
  migration:
    command: bash -c "bundle install -j4 && tail -f /dev/null"
  migration-endtoend:
    ports:
      # http
      - "53303:3303"
      # mysql (vtgate)
      - "53306:3306"
  migration-mysql:
    image: mysql:8.0
    container_name: migration-mysql
    ports:
      - "18306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    networks:
      - migration-default
