services:
  migration:
    command: bash -c "git config --global --add safe.directory /migration && bin/setup && rake spec"
    depends_on:
      migration-endtoend:
        condition: service_healthy
  migration-endtoend:
    command: bash -c "dockerd-entrypoint.sh & sleep 5 && unset DOCKER_HOST && make migration-test-setup && tail -f /dev/null"
    healthcheck:
      test: [ "CMD-SHELL", "mysql -h 127.0.0.1 -u user -D main-test -e 'SELECT 1;'" ]
      interval: 30s
      timeout: 10s
      retries: 120
      start_period: 1m
