services:
  migration:
    build:
      context: .
      args:
        RUBY_VERSION: ${RUBY_VERSION}
    container_name: migration
    volumes:
      - bundle:/usr/local/bundle
      - .:/migration
    networks:
      - migration-default
  migration-endtoend:
    build: ./test/endtoend
    container_name: migration-endtoend
    privileged: true
    volumes:
      - .:/endtoend
      - tmp:/endtoend/tmp
    networks:
      - migration-default
  migration-mysql:
    image: mysql:8.0
    container_name: migration-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    networks:
      - migration-default

networks:
  migration-default:

volumes:
  bundle:
  tmp:
