services:
  migration:
    command: bash -c "git config --global --add safe.directory /migration && bin/setup && rake spec"
    depends_on:
      migration-endtoend:
        condition: service_healthy
  migration-endtoend:
    command: bash -c "dockerd-entrypoint.sh & sleep 5 && unset DOCKER_HOST && make migration-test-setup && tail -f /dev/null"
    healthcheck:
      test: ["CMD", "make", "keyspace-serving-check"]
      interval: 10s
      timeout: 10s
      retries: 60
      start_period: 1m
