services:
  migration:
    command: bash -c "bin/setup && rake spec"
    depends_on:
      migration-endtoend:
        condition: service_healthy
  migration-endtoend:
    command: bash -c "dockerd-entrypoint.sh & sleep 5 && make migration-test-setup && tail -f /dev/null"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 60
      start_period: 1m
