services:
  migration:
    command: bash -c "bin/setup && git config --global --add safe.directory /migration && rake spec"
    depends_on:
      migration-endtoend:
        condition: service_healthy
  migration-endtoend:
    command: bash -c "dockerd-entrypoint.sh & sleep 5 && unset DOCKER_HOST && make migration-test-setup && tail -f /dev/null"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "user", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 120
      start_period: 1m
