services:
  migration:
    build: .
    command: bash -c "bundle install -j4 && tail -f /dev/null"
    container_name: migration
    volumes:
      - bundle:/usr/local/bundle
      - .:/migration
    networks:
      - migration-default
  migration-endtoend:
    build: ./test/endtoend
    container_name: migration-endtoend
    privileged: true
    volumes:
      - .:/endtoend
      - tmp:/endtoend/tmp
    ports:
      # http
      - "53303:3303"
      # mysql (vtgate)
      - "53306:3306"
    networks:
      - migration-default

networks:
  migration-default:

volumes:
  bundle:
  tmp:
