class RailsSupport
  DATABASE_CONFIG: String

  INIT_CONFIG: String

  @migration_files: [String]
  @rails_root: String

  @schema_backup_path: String

  @schema_path: String

  def create_test_vitess_users: (String)->[String,String]

  def run: (String,String?)-> void

  def run_test_env: (String)->void

  def setup: -> void

  def cleanup : -> void

  private

  def db_config: ->untyped

  def copy_template_file: (*String)-> void

  def rails_new: -> void
end
