class RailsSupport
  DATABASE_CONFIG: String

  INIT_CONFIG: String

  @migration_files: [String]
  @rails_root: String

  @schema_backup_path: String

  @schema_path: String

  def run: (String)-> void

  def setup: -> void

  def cleanup : -> void
end
