source "https://rubygems.org"

gem 'rails', ENV['RAILS_VERSION'] || '~> 7.2.0'
gem "mysql2", "< 0.6.0"
gem 'vitess-activerecord-migration', path: '../../../'  # Path to your local gem for testing

# From https://github.com/DataDog/dd-trace-rb/pull/4298.
# concurrent-ruby 1.3.5 removed dependency on logger, see:
# https://github.com/ruby-concurrency/concurrent-ruby/commit/d7ce956dacd0b772273d39b8ed31a30cff7ecf38
# Unfortunately this broke Rails because ActiveSupport used Logger
# before requiring logger.
# Since the failure happens rather early in rails bootstrapping,
# patching it is difficult, thus downgrade concurrent-ruby.
# The issue is fixed in 7-0-stable and should be shipped in the release
# after 7.0.8.7, at which point the pin of concurrent-ruby should be removed.
# See https://github.com/rails/rails/issues/54263
gem 'concurrent-ruby', '1.3.4'

