name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.1'
          - '3.2'
          - '3.3'
        rails:
          - "~> 7.2.0"
          - "~> 7.1.0"
          - "~> 7.0.0"
          - "~> 6.1.0"

    steps:
    - uses: actions/checkout@v4
    - name: Run the e2e tests
      run: |
        docker compose -f compose.yml -f compose.ci.yml up -d migration-endtoend
        docker compose -f compose.yml -f compose.ci.yml up --exit-code-from migration migration || exit_code=$?

        echo "Finished containers. Fetching logs..."
        docker compose -f compose.yml -f compose.ci.yml logs migration-endtoend
        exit $exit_code
      env:
        RUBY_VERSION: ${{ matrix.ruby }}
        RAILS_VERSION: ${{ matrix.rails }}
