name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.2'

    steps:
    - uses: actions/checkout@v4
    - name: Debug Environment Variables
      run: echo $RUBY_VERSION
      env:
        RUBY_VERSION: ${{ matrix.ruby }}
    - name: Run the e2e tests
      run: docker compose -f compose.yml -f compose.ci.yml up
      env:
        RUBY_VERSION: ${{ matrix.ruby }}
