name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.2'

    steps:
    - uses: actions/checkout@v4
    - name: Run the e2e tests
      run: |
        docker compose -f compose.yml -f compose.ci.yml up -d migration-endtoend
        docker compose -f compose.yml -f compose.ci.yml up migration || exit_code=$
        if [ ! -z "$exit_code" ]; then
          echo "Error starting containers. Fetching logs..."
          docker compose -f compose.yml -f compose.ci.yml logs migration-endtoend
          exit $exit_code
        fi
      env:
        RUBY_VERSION: ${{ matrix.ruby }}
